### ISSUE TITLE
hard-coded init script

### ISSUE THREAD

**Issue by antoinetran** [JamesWoolfenden/terraform-gcp-bastion#6]
Hi,

There is a hard-coded init script path from https://github.com/JamesWoolfenden/terraform-gcp-bastion/blob/master/google_compute_instance.bastion.tf#L25 to
https://github.com/JamesWoolfenden/terraform-gcp-bastion/blob/master/template/install-kube.sh

This results in problems:

- impossibility to change image other than Debian-family image (because the script use apt)
- very very old version of kubectl installed (see https://v1-27.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ for updated install version)

It would be great to make this an option:
- ability to disable it
- ability to put a custom init script

Thanks!

**Comment by JamesWoolfenden** [comment]
Modified in head revision to use externally provided init script. If you have a newer init script to use an example?

**Comment by JamesWoolfenden** [comment]
fixed in latest release

**Comment by antoinetran** [comment]
> Modified in head revision to use externally provided init script. If you have a newer init script to use an example?

Hi @JamesWoolfenden ! Thank you for the fix! Sorry I do not have a newer init script, simply because I do not do anything in this bastion. It only serves as a SSH gateway to my kubernetes cluster. To be fair, if you want to write an init script, to avoid too much maintenance, maybe you can install a simple tool just to show as an example.

Something like:
```
#!/bin/sh

if type toolbox ; then
  echo Case OS: Container-Optimized OS: installing toolbox
  toolbox
elif type apt-get ; then
  echo Case OS: Debian family: installing netcat
  apt-get install netcat
elif type yum ; then
  echo Case OS: Redhat family: installing netcat
  yum install nc
fi
```

Then there is no need to maintain this script! I haven't tested it yet.
